### PR TITLE
Multiple @OptArg support

### PR DESCRIPTION
**Pull request by raccoman**
I've recoded the ArgumentParse#parseArguments method to handle commands with multiple optional arguments.
The idea behind what i've written is: Taking into consideration that the arguments are passed in order... When we encounter an optional argument we take the value from CommandArgs#next then we call DrinkProvider#provide and we catch if it throws CommandExitMessage, in case we get the value from CommandParameter#getDefaultOptionalValue and we call again DrinkProvider#provide and if it fails again will be just handle like before in the method that called ArgumentParse#parseArguments, otherwise we call CommandArgs#skip which basically reduce the index of CommandArgs by 1.

### CODE REVIEW

**Comment by jonahseguin** [comment]
Hello, thanks for the PR! Looks good from briefly looking over it.  Did you test in-game?

**Comment by raccoman** [comment]
Of course!

**Comment by raccoman** [comment]
I've been using this fork for a week now, and testing it with pretty much every case, and it doesn't seem to give any errors. In any case since I'm working on a project, if they come up I can lend support.

**Review by jonahseguin — APPROVED** [review]
lgtm

**Pull request merged**
